[package]
name = "wikimind-tauri"
version = "0.1.0"
edition = "2021"

[lib]
name = "wikimind_tauri"
path = "src/lib.rs"

[[bin]]
name = "wikimind-tauri"
path = "src/main.rs"

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

wikimind-commands = { path = "../wikimind/commands" }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tracing-appender = "0.2.4"
tracing = "0.1.44"
tauri-plugin-dialog = "2.7.0"

[build-dependencies]
tauri-build = { version = "2", features = [] }
